# Generated by Django 2.0.5 on 2019-12-27 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20191125_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
                ('company_location', models.CharField(max_length=100)),
                ('company_city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=20)),
                ('employee_salary', models.IntegerField()),
                ('employee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Company')),
                ('employee_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Employee')),
            ],
        ),
    ]
