# Generated by Django 2.0.5 on 2019-12-27 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20191226_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.Employee'),
        ),
    ]
